import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { NextUIProvider } from '@nextui-org/react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import TopButton from '@/components/TopButton';
import QueryProvider from './provider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer autoClose={1500} stacked draggable />
        <QueryProvider>
          <NextUIProvider>
            <Header />
            {children}
            <TopButton />
            <Footer />
          </NextUIProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
